redis:
  image: docker.io/bitnami/redis:6.2
  env_file:
    - env/master.env
  ports:
    - '6379:6379'
  volumes:
    - redis_data:/bitnami/redis/data
redis-replica:
  image: docker.io/bitnami/redis:6.2
  env_file:
    - env/replica.env
  ports:
    - '6380:6379'
  volumes:
    - redis_data:/bitnami/redis/data
volumes:
  redis_data:
    driver: local