spring:
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: redis
    port: 6379
    password: admin$$$
    ssl: true

redis:
  replica:
    host: redis-replica
    port: 6379